[package]
name = "strategy"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
common = { path = "../common" }
datalayer = { path = "../datalayer" }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
chrono.workspace = true
